// For building the open-source release of TalkBack.

ext {
    talkbackApplicationId = "app.talkbackfoss"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

android {
        compileSdk {
            version = release(36) {
                it.minorApiLevel = 1
            }
        }
    buildToolsVersion '36.1.0'
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    buildFeatures {
        buildConfig = true
    }
    defaultConfig {
        buildConfigField "String", "APPLICATION_ID", "\"" + talkbackApplicationId + "\""
        vectorDrawables.useSupportLibrary = true
        minSdk 26
        ndk {
            ndkVersion = "29.0.14206865"
            abiFilters.clear()
            abiFilters.addAll(['arm64-v8a'])
        }
    }
    flavorDimensions "target"
    productFlavors {
        phone {
            dimension "target"
        }
    }
    lint {
        abortOnError = false
    }
}

dependencies {

    // Google common
    implementation 'com.google.guava:guava:33.5.0-jre'
    implementation 'com.google.android.material:material:1.13.0'

    // Support library
    implementation 'androidx.annotation:annotation:1.9.1'
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.browser:browser:1.9.0'
    implementation 'androidx.collection:collection:1.5.0'
    implementation 'androidx.core:core:1.17.0'
    implementation 'androidx.fragment:fragment:1.8.9'
    implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.1.0'
    implementation 'androidx.preference:preference:1.2.1'
    implementation 'androidx.recyclerview:recyclerview:1.4.0'
    implementation 'androidx.viewpager2:viewpager2:1.1.0'

    // Nullable
    implementation 'org.checkerframework:checker-qual:3.52.0'

    // Auto-value
    implementation 'com.google.auto.value:auto-value-annotations:1.11.1'
    annotationProcessor 'com.google.auto.value:auto-value:1.11.1'

    // Cloud services
    implementation 'com.mcxiaoke.volley:library:1.0.19'

}
